version: "3.9"

services:
  backend:
    build: ./backend/app
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/sensor_reader
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    depends_on:
      db:
        condition: service_healthy
    command: uvicorn main:app --host 0.0.0.0 --reload

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sensor_reader
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
